export const ACTIONS = {
  ARCHIVE_ALL_CARD_IN_LIST: "archive-all-card-in-list",
  ARCHIVE_CARD: "archive-card",
  ARCHIVE_LIST: "archive-list",
  CHANGE_LIST_BACKGROUND: "change-list-background",
  COPY_LIST: "copy-list",
  CREATE_LIST: "create-list",
  CREATE_CARD: "create-card",
  MOVE_CARD: "move-card",
  MOVE_CARDS_IN_THIS_LIST: "move-cards-in-this-list",
  MOVE_LIST: "move-list",
  SORT_LIST: "sort-list",
  TOGGLE_CARD_COMPLETION: "toggle-card-completion",
  TOGGLE_COLLAPSE_LIST: "toggle-collapse-list",
  TOGGLE_PIN_LIST: "toggle-pin-list",
  UPDATE_BOARD_TITLE: "update-board-title",
  UPDATE_LIST_TITLE: "update-list-title",
  UPDATE_CARD_TITLE: "update-card-title",
} as const;
